import numpy as np
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

# plot range for y-axis
ymin=-5
ymax=5
fontsize = 12
title = 'Bandstructrue of SmB$_6$'
dlines=[100, 200, 341, 514, 655] # vertical line intervals
xticks=(0,100, 200, 341, 514, 655 ,757)
xticklabels=('Γ', 'X', 'M', 'Γ', 'R', 'X|R', 'M')
lw=1.0 # line width

## the information of elements and orbitals
elem=['Sm','B']
ielem=np.array([1,6],dtype=np.int32) # number of atoms for each element
orb=[['s', 's', 'p', 'p', 'd', 'd', 'f', 'f'],['s','p']]  # projectors for each element
color=['g','r','black', 'cyan']
label=['B s', 'B p', 'Sm 3d', 'Sm 4f']
odos=[[8,10,12,14,16,18],
[9,11,13,15,17,19],
[4],
[6]]
# oo, orbital index for each kind of color, oo can be generated by the following commands
#grep '[a-zA-Z]' sno.projwfc_up |grep 'Li  2S'|awk '{printf( $1-1",")}'    for 2S of Li
#grep '[a-zA-Z]' sno.projwfc_up |grep 'C   2S'|awk '{printf( $1-1",")}'    for 2S of C
oo=[[32,36,40,44,48,52],
[33,34,35,37,38,39,41,42,43,45,46,47,49,50,51,53,54,55],
[8,9,10,11,12],
[18,19,20,21,22,23,24]]

with open('dos.dat') as dos:
    lines=dos.readline()
efermi=float(lines.split()[-2])

feig=open('bd.dat')
l=feig.readline()
nbnd=int(l.split(',')[0].split('=')[1])
nks=int(l.split(',')[1].split('=')[1].split('/')[0])

eig=np.zeros((nks,nbnd),dtype=float)
for i in range(nks):
    l=feig.readline()
    count=0
    if nbnd%10==0:
        n=nbnd//10
    else:
        n=nbnd//10+1
    for j in range(n):
        l=feig.readline()
        for k in range(len(l.split())):
            eig[i][count]=l.split()[k]
            count=count+1

feig.close()

F=plt.gcf()
F.set_size_inches([9,5])
grid = plt.GridSpec(1, 3)

p1=plt.subplot(grid[0,0:2])

for i in range(nbnd):
    line1=plt.plot(np.arange(0,nks), eig[:,i]-efermi,color='grey',lw=lw )

for i in range(len(dlines)):
    vline=dlines[i]
    plt.axvline(x=vline, ymin=ymin, ymax=ymax,lw=lw,ls='--',color='black')
plt.axhline(xmin=0, xmax=nks, y=0, lw=lw,color='black',ls='--')

N=len(elem)
iorb=np.zeros([N,],dtype=np.int32)  # number of projectors for each element
for i in range(N):
    iorb[i]=len(orb[i])

lorb=np.zeros([N,],dtype=np.int32) # number of local orbital for each element
for i in range(N):
    for j in orb[i]:
        if j == 's':
            lorb[i]+=1
        elif j == 'p':
            lorb[i]+=3
        elif j == 'd':
            lorb[i]+=5
        elif j == 'f':
            lorb[i]+=7
        else:
            print("unexpect: ",j)
            assert False

nlorb=np.dot(ielem,lorb)
num_file = np.dot(ielem, iorb)
nat = np.sum(ielem)
D = []
#scf ATOMIC_POSITIONS should be sorted in the same order as above
count=0
count_at=0
for n in range(N):
    for i in range(ielem[n]):
        for j in range(iorb[n]):
            print(n,i,j,count_at+1,elem[n],j+1,orb[n][j])
            fname='sno.pdos_atm#{}({})_wfc#{}({})'.format(count_at+1,elem[n],j+1,orb[n][j])
            D.append(np.loadtxt(fname,dtype=np.float32))
            count+=1
        count_at+=1

pjsum=np.zeros([nlorb, nks, nbnd], dtype=np.float32)

filproj=open('sno.projwfc_up')
nline_io_header=15 # line number at '    F    F'

for i in range(nline_io_header):
    filproj.readline()

for i in range(nlorb):
    filproj.readline()
    for j in range(nks):
        for k in range(nbnd):
            pjsum[i,j,k]=float(filproj.readline().split()[2])

nplotline=np.sum(iorb)

s_of_o=np.zeros([nks,],dtype=np.float32)

scale=90.0
st=[]
for i in range(len(oo)):
    for k in range(nbnd):
        s_of_o=np.zeros([nks,],dtype=np.float32)
        for j in oo[i]:
            s_of_o[:]+=pjsum[j,:,k]
        if k == 0:
            st.append(plt.scatter(-1, ymin-1, 20, c=color[i], alpha=0.5, label=label[i],marker='.',edgecolor='none'))
        st.append(plt.scatter(np.arange(0,nks), eig[:,k]-efermi, s=scale*s_of_o, c=color[i], alpha=0.5, marker='.',edgecolor='none'))

plt.xlim([0,nks-1]) # 201 points
plt.ylabel('E-E${_F}$ (eV)',fontsize=12)
plt.xticks(xticks,xticklabels, fontsize=12)
plt.title(title, fontsize=12)

plt.subplots_adjust(left=0.20, right=0.75, top=0.95, bottom=0.1)

#plt.ylim([-16,20])
#plt.savefig('pband_whole.png',dpi=1000)
plt.ylim([ymin,ymax])

p2=plt.subplot(grid[0,2])
for i in range(len(odos)):
    pdos = np.zeros([len(D[0][:,0]),])
    for j in odos[i]:
        pdos += D[j][:,1]
    line1 = plt.plot(pdos,D[0][:,0]-efermi,color=color[i],lw=lw,label=label[i])
plt.xlim(xmin=0,xmax=9)
plt.ylim([ymin,ymax])
plt.xlabel('DOS (a.u.)',fontsize=fontsize)
plt.xticks([])
plt.ylabel('')
plt.yticks([])
plt.legend()

plt.savefig('pbanddos.png',dpi=1000)
